stages:
  data_ingestion:
    cmd: python src/deepClassifier/pipeline/stg_01_data_ingestion.py
    deps:
      - src/deepClassifier/pipeline/stg_01_data_ingestion.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/PetImages